app/urls.py
from django.urls import path
from . import views

app_name = 'app'
urlpatterns = [
    path('', views.index, name='index'),

    # Registro y autenticación
    path('registro/', views.form_registro, name='form_registro'),
    path('registro_post/', views.post_registro, name='post_registro'),
    path('bienvenida/', views.bienvenida, name='bienvenida'),
    path('login/', views.form_login, name='form_login'),
    path('login_post/', views.post_login, name='post_login'),
    path('logout/', views.post_logout, name='post_logout'),

    # Peliculas
    path('peliculas/', views.peliculas, name='peliculas'),
    path('peliculas/<int:id>/', views.pelicula, name='pelicula'),
    path('peliculas/crear', views.form_crear_pelicula, name='form_crear_pelicula'),
    path('peliculas/crear_post', views.post_crear_pelicula, name='post_crear_pelicula'),

    # Categorias
    path('categorias/', views.categorias, name='categorias'),
    path('categorias/crear', views.form_crear_categoria, name='form_crear_categoria'),
    path('categorias/crear_post', views.post_crear_categoria, name='post_crear_categoria'),

    # Otras paginas
    path('acercade/', views.acercade, name='acercade'),
]

blockbuster/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('app.urls')),
    path('admin/', admin.site.urls),
]

app/models.py
from django.db import models

class Categoria(models.Model):
    nombre = models.CharField(max_length=100)
    descripcion = models.TextField()

    def __str__(self):
        return self.nombre

    class Meta():
        app_label: 'app'


class Pelicula(models.Model):
    titulo = models.CharField(max_length=200)
    anio = models.IntegerField(null=True)
    sinopsis = models.TextField()
    actores = models.TextField(null=True)
    categoria = models.ForeignKey(
        Categoria,
        related_name='peliculas',
        on_delete=models.PROTECT
    )

    def __str__(self):
        return self.titulo

    class Meta:
        app_label: 'app'

app/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404

from .models import Categoria, Pelicula

def index(request):
    return render(request, 'app/index.html')

def acercade(request):
    return render(request, 'app/acercade.html')

@login_required
def peliculas(request):
    # Obtiene las peliculas
    lista = Pelicula.objects.all().order_by('anio')
    # Crea el contexto
    contexto = {
        'peliculas': lista
    }
    return render(request, 'app/peliculas.html', contexto)

@login_required
def pelicula(request, id):
    # Obtiene la pelicula. Si no la encuentra genera el error 404
    obj_pelicula = get_object_or_404(Pelicula, pk=id)
    #obj_pelicula = Pelicula.objects.get(pk=id)
    # Crea el contexto
    contexto = {
        'pelicula': obj_pelicula
    }
    # Muestra el template con la información del contexto
    return render(request, 'app/pelicula.html', contexto)

@login_required
def categorias(request):
    # Obtiene todas las categorias
    lista = Categoria.objects.all()
    # Crea el contexto
    contexto = {
        'categorias': lista
    }
    # Invoca el template enviando el contexto
    return render(request, 'app/categorias.html', contexto)

@login_required
def form_crear_categoria(request):
    return render(request, 'app/formCrearCategoria.html')

@login_required
def post_crear_categoria(request):
    # Obtiene el usuario autenticado
    usuario = request.user
    # Obtiene el nombre de la categoria
    nombre = request.POST['nombre']
    # Crea el objeto
    cat = Categoria(nombre=nombre)
    # Guarda el objeto en la bd
    cat.save()
    # Redirecciona la pagina de categorias
    return redirect('app:categorias')


@login_required
def form_crear_pelicula(request):
    # Obtiene las categorias
    lista_categorias = Categoria.objects.all().order_by('nombre')
    # Crea el contexto
    contexto = {
        'categorias': lista_categorias
    }
    # Muestra el template con el contexto
    return render(request, 'app/formCrearPelicula.html', contexto)


@login_required
def post_crear_pelicula(request):
    # Obtiene los datos del formulario
    titulo = request.POST['titulo'] 
    anio = request.POST['anio'] 
    sinopsis = request.POST['sinopsis'] 
    actores = request.POST['actores'] 
    id_categoria = int(request.POST['categoria'])

    # Obtiene la categoria
    categoria = Categoria.objects.get(pk=id_categoria)

    # Crea el objeto Pelicula
    nueva_pelicula = Pelicula()
    nueva_pelicula.titulo = titulo
    nueva_pelicula.anio = anio
    nueva_pelicula.sinopsis = sinopsis
    nueva_pelicula.actores = actores
    nueva_pelicula.categoria = categoria

    # GUarda el objeto en la BD
    nueva_pelicula.save()
    
    # Redirecciona a la pagina de peliculas
    return redirect('app:peliculas')


def form_registro(request):
    return render(request, 'app/registro.html')


def post_registro(request):
    # Obtiene los datos del formulario
    nombres = request.POST['nombres'] 
    usuario = request.POST['usuario'] 
    email = request.POST['email'] 
    clave = request.POST['clave'] 

    # Crea el objeto
    u = User()
    u.username = usuario
    u.first_name = nombres
    u.email = email
    u.set_password(clave)

    # Guarda el objeto en BD
    u.save()

    return redirect('app:bienvenida')


def bienvenida(request):
    return render(request, 'app/bienvenida.html')


def form_login(request):
    return render(request, 'app/login.html')    


def post_login(request):
    # Obtiene los datos del formulario
    usuario = request.POST['usuario'] 
    clave = request.POST['clave'] 

    # Verifica si existe un usuario con las credenciales
    u = authenticate(username=usuario, password=clave)

    if u is None:
        return HttpResponse('<h1>Usuario o clave incorrectas!!!</h1><p>Revise los datos digitados</p>')   
    else:
        # Autentica el usuario en el sistema
        login(request, u)
        # Redirección al home
        return redirect('app:index')


        
def post_logout(request):
    # Cierra la sesión
    logout(request)
    # Redirección al home
    return redirect('app:index')    

    

app/templates/app/acercade.html
{% extends 'app/layout.html' %}

{% block contenido %}

<h1>Una página hecha en Colombia</h1>
<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Neque eos laboriosam hic nobis asperiores optio, labore expedita quasi commodi molestiae illo explicabo ullam minus, cum adipisci beatae consectetur rerum ad?</p>
<hr>
<h3>Somos una startup</h3>
<ul>
    <li>Hugo</li>
    <li>Paco</li>
    <li>Luis</li>
</ul>

{% endblock %}

app/templates/app/bienvenida.html
{% extends 'app/layout.html' %}

{% block contenido %}

<h1>Bienvenido a BLOCKBUSTER</h1>
<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Aliquid, repellendus perspiciatis provident ad voluptatem quae magnam facere rerum totam possimus deserunt doloremque sit ullam. Blanditiis mollitia a laborum quos sit.</p>


{% endblock %}

app/templates/app/categorias.html
{% extends 'app/layout.html' %}

{% block titulo %}
Categorías
{% endblock %}

{% block contenido %}
<h1>Categorías</h1>

{% if request.user.is_superuser %}
<a href="{% url 'app:form_crear_categoria' %}">Crear categoría</a>
{% endif %}
<ul>
    {% for c in categorias %}
        <li>{{ c.nombre }}</li>
    {% endfor %}
</ul>
{% endblock %}

app/templates/app/formCrearCategoria.html
{% extends 'app/layout.html' %}

{% block titulo %}
Crear categoría
{% endblock %}

{% block contenido %}

<form 
    action="{% url 'app:post_crear_categoria' %}" method="POST">
    {% csrf_token %}
    <label for="nombre">Nombre de categoría</label>
    <input type="text" name="nombre">
    <button type="submit">Crear</button>
</form>

{% endblock %}

app/templates/app/formCrearPelicula.html
{% extends 'app/layout.html' %}

{% block titulo %}
Crear pelicula
{% endblock %}

{% block contenido %}
<form action="{% url 'app:post_crear_pelicula' %}" method="POST">  
    {% csrf_token %}  
    <label for="titulo">Titulo</label>
    <input type="text" name="titulo">
    <br>
    <label for="anio">Año</label>
    <input type="number" name="anio">
    <br>
    <label for="sinopsis">Sinopsis</label>
    <textarea name="sinopsis" cols="30" rows="10"></textarea>
    <br>
    <label for="actores">Actores</label>
    <input type="text" name="actores">
    <br>
    <label for="categoria">Categoría</label>
    <select name="categoria">
        {% for c in categorias %}
        <option value="{{ c.id }}">{{ c.nombre }}</option>
        {% endfor %}
    </select>
    <br>
    <button type="submit">Crear</button>
</form>


{% endblock %}

app/templates/app/index.html
{% extends 'app/layout.html' %}

{% block contenido %}
<h1>BLOCKBUSTER</h1>

{% if request.user.is_authenticated %}

<p>Hola {{ request.user.first_name }}!!!</p>

{% else %}

<p>Si deseas ingresar a nuestro sistema haz click <a href="{% url 'app:form_login' %}">aqui</a></p>

{% endif %}

{% endblock %}

app/templates/app/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Blockbuster</title>
    <link rel="stylesheet" href="{% static 'app/css/estilo.css' %}">
</head>

<body>

    <div class="container">
        <div class="header">
            <h1>
                <img src="{% static 'app/img/bb-logo.png' %}" alt="BB">
                BLOCKBUSTER- <small>{% block titulo %}El mejor sitio{% endblock %}</small></h1>
        </div>
        <div class="navegacion">
            <ul>
                {% if request.user.is_authenticated %}
                <li><a href="{% url 'app:post_logout' %}">Salir</a></li>
                {% else %}
                <li><a href="{% url 'app:form_login' %}">Ingresar</a></li>
                <li><a href="{% url 'app:form_registro' %}">Registro</a></li>
                {% endif %}              

                <li><a href="{% url 'app:index' %}">Inicio</a></li>
                {% if request.user.is_authenticated %}
                <li><a href="{% url 'app:peliculas' %}">Peliculas</a></li>
                <li><a href="{% url 'app:categorias' %}">Categorías</a></li>
                {% endif %}
                <li><a href="{% url 'app:acercade' %}">Nosotros</a></li>
            </ul>
        </div>
        <div class="contenido">
            {% block contenido %}
            {% endblock %}
        </div>
        <div class="footer">
            <span>Derechos reservados - Blockbuster &copy;</span>
        </div>
    </div>

    <script src="{% static 'app/js/index.js' %}"></script>
</body>

</html>

app/templates/app/login.html
{% extends 'app/layout.html' %}

{% block titulo %}
Ingreso
{% endblock %}

{% block contenido %}

<h1>Ingreso a BLOCKBUSTER</h1>

<form action="{% url 'app:post_login' %}" method="POST">
    {% csrf_token %}
    <label for="usuario">Usuario</label>
    <input type="text" name="usuario">
    <br>
    <label for="clave">Clave</label>
    <input type="password" name="clave">
    <br>
    <button type="submit">Ingresar</button>
</form>

{% endblock %}

app/templates/app/pelicula.html
{% extends 'app/layout.html' %}

{% block contenido %}
{% if pelicula %}
<h1>{{ pelicula.titulo }}</h1>
<h3>Año</h3>
<p>{{ pelicula.anio }}</p>

{% if pelicula.actores %}
<h3>Actores</h3>
<p>{{ pelicula.actores }}</p>
{% endif %}

<h3>Sinopsis</h3>
<p>{{ pelicula.sinopsis }}</p>
{% else %}
<h1 style="color: red">La película solicitada no existe!</h1>
{% endif %}

{% endblock %}

app/templates/app/peliculas.html
{% extends 'app/layout.html' %}

{% block titulo %}
Películas
{% endblock %}

{% block contenido %}
{% if request.user.is_superuser %}
<a href="{% url 'app:form_crear_pelicula' %}">Crear película</a>
{% endif %}
<table border="1">
    <thead>
        <tr>
            <th>Titulo</th>
            <th>Año</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        {% for p in peliculas %}
        <tr>
            <td>{{ p.titulo }}</td>
            <td>{{ p.anio }}</td>
            <td>
                <a href="{% url 'app:pelicula' p.id %}">Ver</a>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

app/templates/app/registro.html
{% extends 'app/layout.html' %}

{% block titulo %}
Registro
{% endblock %}

{% block contenido %}
<h1>Datos del usuario</h1>

<form action="{% url 'app:post_registro' %}" method="post">
    {% csrf_token %}
    <label for="nombres">Nombres</label>
    <input type="text" name="nombres">
    <br>
    <label for="username">Usuario</label>
    <input type="text" name="usuario">
    <br>
    <label for="email">Email</label>
    <input type="email" name="email">
    <br>
    <label for="password">Contraseña</label>
    <input type="password" name="clave">
    <br>
    <button type="submit">Crear cuenta</button>

</form>


{% endblock %}